services:
  postgres:
    image: postgres:17
    container_name: postgres-test
    restart: on-failure
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-lockboxuser} -d ${DB_NAME:-lockboxdb}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  postgres_test_data:

networks:
  test-network:
    driver: bridge
