services:
  lockbox:
    image: lockbox:latest
    container_name: lockbox
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    command:
      - "--config-file"
      - "/etc/lockbox/lockbox.conf"
    volumes:
      - ./../lockbox.conf:/etc/lockbox/lockbox.conf
    networks:
      - lockbox-network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER:-lockboxuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-lockboxdb}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-lockboxuser} -d ${DB_NAME:-lockboxdb}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lockbox-network

volumes:
  postgres_data:

networks:
  lockbox-network:
    driver: bridge
